/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/_main'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MainWalletRouteImport } from './routes/_main.wallet'
import { Route as MainTransactionsRouteImport } from './routes/_main.transactions'
import { Route as MainSettingsRouteImport } from './routes/_main.settings'
import { Route as MainProfileRouteImport } from './routes/_main.profile'
import { Route as MainOrdersRouteImport } from './routes/_main.orders'
import { Route as MainMarketplaceRouteImport } from './routes/_main.marketplace'
import { Route as MainItemsRouteImport } from './routes/_main.items'
import { Route as MainDashboardRouteImport } from './routes/_main.dashboard'
import { Route as AuthRegisterRouteImport } from './routes/_auth.register'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as MainWalletCreateRouteImport } from './routes/_main.wallet.create'
import { Route as MainOrdersCreateRouteImport } from './routes/_main.orders.create'
import { Route as MainItemsItemIdRouteImport } from './routes/_main.items.$itemId'

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainWalletRoute = MainWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => MainRoute,
} as any)
const MainTransactionsRoute = MainTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => MainRoute,
} as any)
const MainSettingsRoute = MainSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MainRoute,
} as any)
const MainProfileRoute = MainProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MainRoute,
} as any)
const MainOrdersRoute = MainOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => MainRoute,
} as any)
const MainMarketplaceRoute = MainMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => MainRoute,
} as any)
const MainItemsRoute = MainItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => MainRoute,
} as any)
const MainDashboardRoute = MainDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => MainRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const MainWalletCreateRoute = MainWalletCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => MainWalletRoute,
} as any)
const MainOrdersCreateRoute = MainOrdersCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => MainOrdersRoute,
} as any)
const MainItemsItemIdRoute = MainItemsItemIdRouteImport.update({
  id: '/$itemId',
  path: '/$itemId',
  getParentRoute: () => MainItemsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/dashboard': typeof MainDashboardRoute
  '/items': typeof MainItemsRouteWithChildren
  '/marketplace': typeof MainMarketplaceRoute
  '/orders': typeof MainOrdersRouteWithChildren
  '/profile': typeof MainProfileRoute
  '/settings': typeof MainSettingsRoute
  '/transactions': typeof MainTransactionsRoute
  '/wallet': typeof MainWalletRouteWithChildren
  '/items/$itemId': typeof MainItemsItemIdRoute
  '/orders/create': typeof MainOrdersCreateRoute
  '/wallet/create': typeof MainWalletCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/dashboard': typeof MainDashboardRoute
  '/items': typeof MainItemsRouteWithChildren
  '/marketplace': typeof MainMarketplaceRoute
  '/orders': typeof MainOrdersRouteWithChildren
  '/profile': typeof MainProfileRoute
  '/settings': typeof MainSettingsRoute
  '/transactions': typeof MainTransactionsRoute
  '/wallet': typeof MainWalletRouteWithChildren
  '/items/$itemId': typeof MainItemsItemIdRoute
  '/orders/create': typeof MainOrdersCreateRoute
  '/wallet/create': typeof MainWalletCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_main': typeof MainRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_main/dashboard': typeof MainDashboardRoute
  '/_main/items': typeof MainItemsRouteWithChildren
  '/_main/marketplace': typeof MainMarketplaceRoute
  '/_main/orders': typeof MainOrdersRouteWithChildren
  '/_main/profile': typeof MainProfileRoute
  '/_main/settings': typeof MainSettingsRoute
  '/_main/transactions': typeof MainTransactionsRoute
  '/_main/wallet': typeof MainWalletRouteWithChildren
  '/_main/items/$itemId': typeof MainItemsItemIdRoute
  '/_main/orders/create': typeof MainOrdersCreateRoute
  '/_main/wallet/create': typeof MainWalletCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/items'
    | '/marketplace'
    | '/orders'
    | '/profile'
    | '/settings'
    | '/transactions'
    | '/wallet'
    | '/items/$itemId'
    | '/orders/create'
    | '/wallet/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/items'
    | '/marketplace'
    | '/orders'
    | '/profile'
    | '/settings'
    | '/transactions'
    | '/wallet'
    | '/items/$itemId'
    | '/orders/create'
    | '/wallet/create'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_main'
    | '/_auth/login'
    | '/_auth/register'
    | '/_main/dashboard'
    | '/_main/items'
    | '/_main/marketplace'
    | '/_main/orders'
    | '/_main/profile'
    | '/_main/settings'
    | '/_main/transactions'
    | '/_main/wallet'
    | '/_main/items/$itemId'
    | '/_main/orders/create'
    | '/_main/wallet/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  MainRoute: typeof MainRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/wallet': {
      id: '/_main/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof MainWalletRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/transactions': {
      id: '/_main/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof MainTransactionsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/settings': {
      id: '/_main/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof MainSettingsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/profile': {
      id: '/_main/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof MainProfileRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/orders': {
      id: '/_main/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof MainOrdersRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/marketplace': {
      id: '/_main/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MainMarketplaceRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/items': {
      id: '/_main/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof MainItemsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/dashboard': {
      id: '/_main/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof MainDashboardRouteImport
      parentRoute: typeof MainRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_main/wallet/create': {
      id: '/_main/wallet/create'
      path: '/create'
      fullPath: '/wallet/create'
      preLoaderRoute: typeof MainWalletCreateRouteImport
      parentRoute: typeof MainWalletRoute
    }
    '/_main/orders/create': {
      id: '/_main/orders/create'
      path: '/create'
      fullPath: '/orders/create'
      preLoaderRoute: typeof MainOrdersCreateRouteImport
      parentRoute: typeof MainOrdersRoute
    }
    '/_main/items/$itemId': {
      id: '/_main/items/$itemId'
      path: '/$itemId'
      fullPath: '/items/$itemId'
      preLoaderRoute: typeof MainItemsItemIdRouteImport
      parentRoute: typeof MainItemsRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MainItemsRouteChildren {
  MainItemsItemIdRoute: typeof MainItemsItemIdRoute
}

const MainItemsRouteChildren: MainItemsRouteChildren = {
  MainItemsItemIdRoute: MainItemsItemIdRoute,
}

const MainItemsRouteWithChildren = MainItemsRoute._addFileChildren(
  MainItemsRouteChildren,
)

interface MainOrdersRouteChildren {
  MainOrdersCreateRoute: typeof MainOrdersCreateRoute
}

const MainOrdersRouteChildren: MainOrdersRouteChildren = {
  MainOrdersCreateRoute: MainOrdersCreateRoute,
}

const MainOrdersRouteWithChildren = MainOrdersRoute._addFileChildren(
  MainOrdersRouteChildren,
)

interface MainWalletRouteChildren {
  MainWalletCreateRoute: typeof MainWalletCreateRoute
}

const MainWalletRouteChildren: MainWalletRouteChildren = {
  MainWalletCreateRoute: MainWalletCreateRoute,
}

const MainWalletRouteWithChildren = MainWalletRoute._addFileChildren(
  MainWalletRouteChildren,
)

interface MainRouteChildren {
  MainDashboardRoute: typeof MainDashboardRoute
  MainItemsRoute: typeof MainItemsRouteWithChildren
  MainMarketplaceRoute: typeof MainMarketplaceRoute
  MainOrdersRoute: typeof MainOrdersRouteWithChildren
  MainProfileRoute: typeof MainProfileRoute
  MainSettingsRoute: typeof MainSettingsRoute
  MainTransactionsRoute: typeof MainTransactionsRoute
  MainWalletRoute: typeof MainWalletRouteWithChildren
}

const MainRouteChildren: MainRouteChildren = {
  MainDashboardRoute: MainDashboardRoute,
  MainItemsRoute: MainItemsRouteWithChildren,
  MainMarketplaceRoute: MainMarketplaceRoute,
  MainOrdersRoute: MainOrdersRouteWithChildren,
  MainProfileRoute: MainProfileRoute,
  MainSettingsRoute: MainSettingsRoute,
  MainTransactionsRoute: MainTransactionsRoute,
  MainWalletRoute: MainWalletRouteWithChildren,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  MainRoute: MainRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
